### ISSUE TITLE
Funnel New Users Quicker over to Installation 

### ISSUE THREAD

**Issue by AJCastroChandri** [cockpit-project/cockpit-project.github.io#188]
Over [on this page](https://cockpit-project.org/running.html), you should consider adding a text like:
"Click on your distro to see the installation commands."
When a *new* user arrives on the page, there's no clear way to figure out HOW to install cockpit.

In fact, if you search for "installation"  or "install", it is nowhere in that page UNTIL you click on the distro icon.

Another option, which I think would go even beyond, is to remove the "click-icon to reveal".
Just put a list in there:
Fedora: yum install cockpit
CentOS: etc
Debian: apt get install cockpit
Windows: format c:\\
Ubuntu: apt get install cockpit

That would provide it even faster at a glance.
That's the input from someone that had never seen the page... there was no clear way of "how do I install this?!".

**Comment by stefwalter** [comment]
@AJCastroChandri This is good feedback. CC @garrett would you be able to put together a quick fix to add the "Click on your distro ..." line?

**Comment by garrett** [comment]
@AJCastroChandri: Thanks! I made the suggested quick fix of adding a line of text.

I don't think that's quite enough, so I opened #190 for a redesign of that page. We should either make the logos look more clickable by default — without a hover — or show all the text on the page with in-page links.

As this issue is mostly about a quick, I'll close it and we can discuss a redesign on the other issue.

**Comment by garrett** [comment]
@AJCastroChandri: I've reworked the installation page and have a preview of the work-in-progress here: https://garrett.github.io/cockpit-project.github.io/running.html — I'll probably merge something like this to the official website soon. Thanks again for your feedback!

**Comment by garrett** [comment]
The changes have been merged and are now live at https://cockpit-project.org/running.html — clicking on the logo takes you to the right set of instructions (as before), but there's a link at the side. 

And the page is scrollable / scannable and find-in-page works as well... all because it's just a normal webpage without JavaScript-based interactions now. :wink:
