### ISSUE TITLE
Incomplete instructions for getting Cockpit to run on Arch

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit-project.github.io#19]
Under the Arch section on http://cockpit-project.org/running.html it says "Coming soon..."

The reason for that while Cockpit exists for Arch, I'm not familiar enough with how Arch works to be able to write these instructions.

Any help from seasoned Arch users would be very welcome!

**Comment by anatol** [comment]
Arch has `cockpit` and `cockpit-git` packages in AUR. After installing one of of these packages using cockpit should be similar to other platforms.

**Comment by stefwalter** [comment]
@anatol Could you write out the exact commands here that a user would use to accomplish that? Then we can add those commands to the http://cockpit-project.org/running.html web page.

**Comment by anatol** [comment]
`yaourt -S cockpit` would be the simplest way. Though one should understand this is _unsupported_ Arch repository (install scripts come from third-party developers). Users should check carefully what they are installing.

**Comment by stefwalter** [comment]
Yes, @anatol good point.

@andreasn we need to do a better job of indicating which are supported/stable. We currently do that after you click on the OS icon. Should we add a badge to the OS icon itself?

**Comment by andreasn** [comment]
@stefwalter I tried doing that, but was unable to do it in a way that just didn't look terrible.

**Comment by andreasn** [comment]
@anatol So something along the lines of:
"Type `yaourt -S cockpit` into a terminal.
Note, this repository uses scripts from 3rd party developers. Install at your own risk"

**Comment by mrshu** [comment]
While `yaourt` is quite popular wrapper, `packer` is another and there are several other ones.

I strongly agree with what @anatol said and would like to point out what the official Arch Linux Wiki [has to say on this matter](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages):

>  Warning: There is not and will never be an official mechanism for installing build material from the AUR. All AUR users should be familiar with the build process.

The Arch Linux Wiki operates on this assumption, which is why you many times encounter a statement similar to the [Zero Install one](https://wiki.archlinux.org/index.php/Zero_Install) 

> Zero Install can be found in the Arch User Repository as package zeroinstall-injector. 

I believe something along those lines would be the most appropriate for `cockpit` too.
