### ISSUE TITLE
Update screenshots for PF4-ish reskinning

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-project.github.io#255]
When https://github.com/cockpit-project/cockpit/pull/11987 lands, we probably want new screenshots on the website.

**Comment by garrett** [comment]
To everyone: Feel free to upload screenshots here on the issue. I'll add optimized versions of them on a PR.

Thanks!

**Comment by marusak** [comment]
I looked what we currently have and try to recreate them. I havn't done the one from dashboard as I have only one machine set up.  If anyone else would do that that would be great, otherwise I can setup some machines. And also instead of docker I took screenshot of podman containers as it seems to be now the trend :)
![screenshot-podman](https://user-images.githubusercontent.com/12330670/61023899-054ac780-a3ac-11e9-9f4d-2315255c52c2.png)
![screenshot-network](https://user-images.githubusercontent.com/12330670/61024128-eb5db480-a3ac-11e9-812c-538c44a10780.png)
![screenshot-storage](https://user-images.githubusercontent.com/12330670/61023901-054ac780-a3ac-11e9-8b0d-c1193fe7e850.png)
![screenshot](https://user-images.githubusercontent.com/12330670/61023902-05e35e00-a3ac-11e9-8829-6aeafeeb2939.png)

**Comment by martinpitt** [comment]
I did a Dashboard screenshot with three machines and three different OSes:

![dashboard](https://user-images.githubusercontent.com/200109/61025642-a38d5c00-a3b1-11e9-85ae-cd557b34a060.png)

Annoyingly this has a scrollbar, even though there's no content below the server list. That's something  we should fix, too :-)

**Comment by garrett** [comment]
Thanks for the screenshots! However, there are some issues.

@marusak: Your screenshots are using the wrong fonts and have "localhost.localdomain" as the hostname. We cannot use these for that reason. There are also incorrect widgets in some for odd reasons.

@martinpitt: Your screenshot is too wide.

We need to update the screenshots according to the screenshot guidelines @ https://github.com/cockpit-project/cockpit-project.github.io/issues/183

**Comment by garrett** [comment]
We'll need to update the screenshots with the dark nav and search... and make sure they're in accordance with https://github.com/cockpit-project/cockpit-project.github.io/issues/183

**Comment by garrett** [comment]
Resolved in #373.
