### ISSUE TITLE
blog: Performance issues and html validation

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit-project.github.io#61]
This concerns our release notes blog.

Some users have problems waiting for
```
<script src="http://code.jquery.com/jquery-2.0.0.min.js"></script>
```
We should probably switch to a proper CDN for this.

Also
```
 <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=PT+Sans:400,400italic,700|Roboto+Slab:400,700">
```
can fail validation.

**Comment by herrold** [comment]
The particular HTML Validator I use is a Firefox plugin, at: http://users.skynet.be/mgueury/mozilla/

which has sort of 'gamified' getting rid of non-compliant HTML in the generation scripts I maintain

**Comment by garrett** [comment]
The website has changed from Pelican to Jekyll. This issue still applies however, as it's related to webby things in general. I just need to set aside some time in the future to check HTML validation again. 

(I checked validation a while back when developing the base framework the site uses back when I was in OSAS. However, I'm almost sure I probably broke things since. :wink:)

BTW: I think the issue should probably be split in two: CDN (discussion) and HTML validation.

**Comment by garrett** [comment]
A while ago, I checked the website with [HTML Validator](https://addons.mozilla.org/en-US/firefox/addon/html-validator/) (based on Tidy), and I made sure it all passes.

I've checked again today, and it still passes.

The only exception is the guide, which is built with an external tool. The guide has a few warnings, but is otherwise fine.

jQuery itself is now hosted with the site, and the fonts are imported differently (and as of today, use `//` to pull from the same protocol).
